services:
  - type: web
    name: bloume-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FINCRA_SECRET_KEY
        value: your_secret_key
      - key: FINCRA_PUBLIC_KEY  
        value: your_public_key
      - key: FINCRA_BUSINESS_ID
        value: your_business_id